# Permalinks
permalink:           pretty

# Setup
title:               Babak Shahian Jahromi
tagline:             My Data Science Blog
url:                 http://BabakShah.github.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Babak Shahian Jahromi
  url:               https://twitter.com/CuriousBabak
  email:             babakshahanjahromi@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/BabakShah

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
